name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Check if package.json changed
      id: check_version
      run: |
        git diff --name-only HEAD~1 HEAD | grep 'package.json'
        if [ $? -eq 0 ]; then
          echo "::set-output name=version_changed::true"
        else
          echo "::set-output name=version_changed::false"
        fi
      shell: bash
      continue-on-error: true
    
    - name: Run release
      if: steps.check_version.outputs.version_changed == 'true'
      run: npm run release

    - name: Setup Node.js
      if: steps.check_version.outputs.version_changed == 'true'
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      if: steps.check_version.outputs.version_changed == 'true'
      run: npm install

    - name: Build Electron App
      if: steps.check_version.outputs.version_changed == 'true'
      run: npm run build

    - name: Check if gh is already installed
      id: check_gh
      run: |
        if gh --version; then
         echo "::set-output name=installed::true"
        else
          echo "::set-output name=installed::false"
        fi
      shell: bash

    - name: Install GitHub CLI
      if: steps.check_gh.outputs.installed == 'false'
      run: choco install gh --install-arguments="'/l*v c:\gh_msi_install.log'"

    - name: Create GitHub Release and Upload Exe
      if: steps.check_version.outputs.version_changed == 'true'
      run: |
        NEW_VERSION=$(node -p "require('./package.json').version")
        echo "$NEW_VERSION"
        echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token
        gh release create "v$NEW_VERSION" "./dist/*" --title "v$NEW_VERSION" --notes "Release for v$NEW_VERSION"
      shell: bash

