name: Release on Version Tag

on:
  workflow_run:
    workflows: ["Auto Tag Version"]
    types:
      - completed

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Electron App
      run: npm run build

    - name: Release Electron App
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Release ${{ github.ref }}"
        files: |
          dist/*.exe
