name: Release on Tag

on:
  workflow_run:
    workflows: ["Auto Tag Version"]
    types:
      - completed

jobs:
  check-versioning-result:
    runs-on: ubuntu-latest
    steps:
      - name: Check versioning workflow result
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: echo "Versioning workflow failed or was cancelled. Exiting!" && exit 1
        
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Wine
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install --yes wine64 wine32

    - name: Install xvfb and run winecfg silently
      run: |
        sudo apt install --yes xvfb
        xvfb-run winecfg

    - name: Install dependencies
      run: npm install

    - name: Build and Release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npm run release
