name: Auto Tag Version

on:
  push:
    branches:
      - master

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18 

    - name: Check if package.json changed and create a tag
      run: |
        PACKAGE_CHANGED=$(git diff --name-only HEAD~1 HEAD | grep 'package.json')
        if [ "$PACKAGE_CHANGED" ]; then
            NEW_VERSION=$(node -p "require('./package.json').version")
            git tag "v$NEW_VERSION"
            git push origin "v$NEW_VERSION"
        fi
